name: amazon_paapi5
description: Amazon Product Advertising API v5 SDK for Dart & Flutter. Search products, retrieve pricing, images, and affiliate data with built-in AWS Signature V4 signing.
version: 1.0.0
homepage: https://github.com/febin52/amazon_paapi
repository: https://github.com/febin52/amazon_paapi
issue_tracker: https://github.com/febin52/amazon_paapi/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  intl: ^0.19.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  flutter_lints: ^3.0.0
